##
## Version: 1.0.1
##

title: Javanile Packages
tagline: Official Javanile Software Registry
url: https://packages.javanile.org
remote_theme: javanile/package-manager@main
primary_color: "#2C842C"
enable_dark_theme: false

suggested_command: "mush install {package}"

defaults:
  - scope: { path: "" }
    values: { layout: "default" }

collections:
  packages:
    output: true
    permalink: /:collection/:name
  categories:
    output: true
    permalink: /:collection/:name
